# The routes of the project.
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://www.neminis.org/":
  type: upstream
  upstream: "neminis:http"
  cache:
    enabled: true
    # Base the cache on the session cookies. Ignore all other cookies.
    cookies:
      - "/^wordpress_logged_in_/"
      - "/^wordpress_sec_/"
      - "wordpress_test_cookie"
      - "/^wp-settings-/"
      - "/^wp-postpass/"

"https://neminis.org/":
  type: redirect
  to: "https://www.neminis.org/"

"https://www.pergrazia.com/":
  type: upstream
  upstream: "pg:http"
  cache:
    enabled: true
    # Base the cache on the session cookies. Ignore all other cookies.
    cookies:
      - "/^wordpress_logged_in_/"
      - "/^wordpress_sec_/"
      - "wordpress_test_cookie"
      - "/^wp-settings-/"
      - "/^wp-postpass/"

"https://pergrazia.com/":
  type: redirect
  to: "https://www.pergrazia.com/"
