# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

engdb:
  type: mariadb:10.11
  disk: 512

itadb:
  type: mariadb:10.11
  disk: 512

redis:
  type: redis:7.0

es:
  type: elasticsearch:7.10
  disk: 256
